### ISSUE TITLE
Add Score to the game

### ISSUE THREAD

**Issue by llyram** [Maryll-castelino/2048-GAME#1]
Keep track of the score in a box component on top of the board

The value of the new tiles created must be added to the score after every move

Comment below for any clarification

**Comment by andrefpoliveira** [comment]
Hey! Can i work on this? 😁

**Comment by llyram** [comment]
@andrefpoliveira sure

**Comment by hardiksharma11** [comment]
Hello. Can you assign this to me..

**Comment by llyram** [comment]
@hardiksharma11 This issue is already assigned to @andrefpoliveira
